# Vars that need to be set on github:
#   - GODOT_VERSION: Which godot version you are using (ex: 4.1.3)
#   - GODOT_PATH: Relative path from root to where your godot project is (ex: ".", "./godot")
#   - BUILD_PATH: Directory to build to, relative to GODOT_PATH (ex: ../build)
#   - EXPORT_NAME: Name of the files to generate for each build
#   - ITCH_GAME: Name of the Itch.io game to upload build files to
#   - ITCH_USER: Name of the Itch.io user who owns the game (get this from the URL of the game)
#   - DISCORD_MESSAGE: String message to send to the discord via the configured webhook
# Secrets that need to be set on github:
#  - BUTLER_API_KEY: Your API Key from Itch.io
#  - DISCORD_WEBHOOK: Your webhook from Discord
name: "godot-ci export"
on:
  push:
    branches: 
      - main

jobs:
  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Mac Build
        run: |
          mkdir -v -p ${{ vars.BUILD_PATH }}/mac
          godot --headless -v --path ${{ vars.GODOT_PATH }} --export-release "macOS" ${{ vars.BUILD_PATH }}/mac/${{ vars.EXPORT_NAME }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: ${{ vars.BUILD_PATH }}/mac
      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: mac
          ITCH_GAME: ${{ vars.ITCH_GAME }}
          ITCH_USER: ${{ vars.ITCH_USER }}
          PACKAGE: ${{ vars.BUILD_PATH }}/mac

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Web Build
        run: |
          mkdir -v -p ${{ vars.BUILD_PATH }}/web
          godot --headless -v --path ${{ vars.GODOT_PATH }} --export-release "HTML5" ${{ vars.BUILD_PATH }}/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: ${{ vars.BUILD_PATH }}/web
      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ vars.ITCH_GAME }}
          ITCH_USER: ${{ vars.ITCH_USER }}
          PACKAGE: ${{ vars.BUILD_PATH }}/web

      - name: Notify Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: '${{ vars.DISCORD_MESSAGE }}'